### ISSUE TITLE
AttributeError: 'LSTM' object has no attribute 'all_weights'

### ISSUE THREAD

**Issue by cswhjiang** [salesforce/awd-lstm-lm#2]
Failed on pytorch 0.2.0_1
```
python3.6 main.py --batch_size 20 --data data/penn --dropouti 0.4 --seed 28 --epoch 300 --save PTB.pt
[LSTM(400, 1150, dropout=0.3), LSTM(1150, 1150, dropout=0.3), LSTM(1150, 400, dropout=0.3)]
Applying weight drop of 0.5 to weight_hh_l0
Applying weight drop of 0.5 to weight_hh_l0
Applying weight drop of 0.5 to weight_hh_l0
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    model.cuda()
  File "/data1/XXXX/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 147, in cuda
    return self._apply(lambda t: t.cuda(device_id))
  File "/data1/XXXX/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/data1/XXXX/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/data1/XXXX/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/data1/XXXX/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 116, in _apply
    self.flatten_parameters()
  File "/data1/XXXX/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 104, in flatten_parameters
    all_weights = [[p.data for p in l] for l in self.all_weights]
  File "/data1/XXXX/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 262, in __getattr__
    type(self).__name__, name))
AttributeError: 'LSTM' object has no attribute 'all_weights'

```

**Comment by Smerity** [comment]
As noted in the README under [system requirements](https://github.com/salesforce/awd-lstm-lm/blob/acb04a5d86bff8d3867bc1343ce0e4b223b8d5be/README.md#software-requirements):
`This codebase requires Python 3 and PyTorch 0.1.12_2.`

If you wish to submit fixes to allow it to work with PyTorch 0.2 or higher, they'd be welcomed, but for now it's required to use PyTorch 0.1.12_2.
